In [1]:
import numpy as np
import pandas as pd 
import plotly.express as px
import seaborn as sns

In [2]:
data = pd.read_csv('/home/tsoien/github/Research-Group/MLResearch/model/Disease_symptom_and_patient_profile_dataset.csv')


In [3]:
data

Disease Fever Cough Fatigue Difficulty Breathing  Age  Gender  \
0      Influenza   Yes    No     Yes                  Yes   19  Female   
1    Common Cold    No   Yes     Yes                   No   25  Female   
2         Eczema    No   Yes     Yes                   No   25  Female   
3         Asthma   Yes   Yes      No                  Yes   25    Male   
4         Asthma   Yes   Yes      No                  Yes   25    Male   
..           ...   ...   ...     ...                  ...  ...     ...   
344       Stroke   Yes    No     Yes                   No   80  Female   
345       Stroke   Yes    No     Yes                   No   85    Male   
346       Stroke   Yes    No     Yes                   No   85    Male   
347       Stroke   Yes    No     Yes                   No   90  Female   
348       Stroke   Yes    No     Yes                   No   90  Female   

    Blood Pressure Cholesterol Level Outcome Variable  
0              Low            Normal         Positive  
1           Normal            Normal         Negative  
2           Normal            Normal         Negative  
3           Normal            Normal         Positive  
4           Normal            Normal         Positive  
..             ...               ...              ...  
344           High              High         Positive  
345           High              High         Positive  
346           High              High         Positive  
347           High              High         Positive  
348           High              High         Positive  

[349 rows x 10 columns]

In [4]:
data['Disease'].nunique()

116

In [5]:
np.unique(data['Outcome Variable'], return_counts=True)

(array(['Negative', 'Positive'], dtype=object), array([163, 186]))

In [6]:
fig = px.histogram(data_frame=data, x='Age', color='Age')
fig.update_layout(showlegend=False)

fig.show()

In [8]:
Diseases_counts = data['Disease'].value_counts()

In [9]:
Diseases_counts

Disease
Asthma               23
Stroke               16
Osteoporosis         14
Diabetes             10
Hypertension         10
                     ..
Schizophrenia         1
Gout                  1
Testicular Cancer     1
Tonsillitis           1
Williams Syndrome     1
Name: count, Length: 116, dtype: int64

In [10]:
Diseases_counts = Diseases_counts[Diseases_counts >= 4]

In [11]:
Diseases_counts.index


Index(['Asthma', 'Stroke', 'Osteoporosis', 'Diabetes', 'Hypertension',
       'Migraine', 'Influenza', 'Bronchitis', 'Pneumonia', 'Hyperthyroidism',
       'Hypothyroidism', 'Eczema', 'Kidney Cancer', 'Depression',
       'Liver Cancer', 'Osteoarthritis', 'Gastroenteritis',
       'Rheumatoid Arthritis', 'Allergic Rhinitis', 'Common Cold',
       'Anxiety Disorders', 'Liver Disease', 'Psoriasis', 'Kidney Disease',
       'Pancreatitis', 'Multiple Sclerosis', 'Ulcerative Colitis',
       'Urinary Tract Infection', 'Parkinson's Disease', 'Crohn's Disease',
       'Coronary Artery Disease', 'Alzheimer's Disease',
       'Chronic Obstructive Pulmonary Disease (COPD)'],
      dtype='object', name='Disease')

In [12]:
Diseases_counts.values

array([23, 16, 14, 10, 10, 10,  8,  8,  8,  7,  7,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4])

In [13]:
px.pie(Diseases_counts, names=Diseases_counts.index, values=Diseases_counts.values)

In [15]:
X = data.drop('Outcome Variable', axis=1).values
y = data['Outcome Variable'].values

In [16]:
X.shape, y.shape

((349, 9), (349,))

In [17]:
from sklearn.preprocessing import LabelEncoder, StandardScaler


In [18]:
label = LabelEncoder()


X[:, 0] = label.fit_transform(X[:, 0])
X[:, 1] = label.fit_transform(X[:, 1])
X[:, 2] = label.fit_transform(X[:, 2])
X[:, 3] = label.fit_transform(X[:, 3])
X[:, 4] = label.fit_transform(X[:, 4])
X[:, 5] = label.fit_transform(X[:, 5])
X[:, 6] = label.fit_transform(X[:, 6])
X[:, 7] = label.fit_transform(X[:, 7])
X[:, 8] = label.fit_transform(X[:, 8])

In [19]:
scaler_x = StandardScaler()

X = scaler_x.fit_transform(X)  

In [20]:
X

array([[ 0.02030724,  0.99713876, -0.95790522, ..., -0.99144064,
         0.00882697,  1.1053115 ],
       [-0.94476192, -1.00286945,  1.04394462, ..., -0.99144064,
         1.03569737,  1.1053115 ],
       [-0.55270257, -1.00286945,  1.04394462, ..., -0.99144064,
         1.03569737,  1.1053115 ],
       ...,
       [ 1.37743575,  0.99713876, -0.95790522, ...,  1.00863325,
        -1.01804343, -1.00263229],
       [ 1.37743575,  0.99713876, -0.95790522, ..., -0.99144064,
        -1.01804343, -1.00263229],
       [ 1.37743575,  0.99713876, -0.95790522, ..., -0.99144064,
        -1.01804343, -1.00263229]])

In [21]:
y

array(['Positive', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Negative', 'Negative',
       'Positive', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Positive', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Negative', 'Negative', 'Positive', 'Positive', 'Positive',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negati

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [24]:
X_train.shape, y_train.shape

((244, 9), (244,))

In [25]:
X_test.shape, y_test.shape

((105, 9), (105,))

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
clf = RandomForestClassifier(criterion="gini", n_estimators=20, random_state=0)

In [28]:
clf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20, random_state=0)

In [31]:
from sklearn.metrics import classification_report

# Predict the labels for the test set
y_pred = clf.predict(X_test)

# Generate the classification report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

    Negative       0.82      0.77      0.80        53
    Positive       0.78      0.83      0.80        52

    accuracy                           0.80       105
   macro avg       0.80      0.80      0.80       105
weighted avg       0.80      0.80      0.80       105



In [30]:
X_test

array([[ 0.02030724,  0.99713876,  1.04394462,  0.66494267,  1.72218149,
        -1.88519226, -0.99144064,  1.03569737,  1.1053115 ],
       [-0.94476192,  0.99713876, -0.95790522,  0.66494267,  1.72218149,
        -1.23053346,  1.00863325, -1.01804343, -1.00263229],
       [ 1.64886145, -1.00286945,  1.04394462, -1.50388904, -0.58065889,
         0.73344296,  1.00863325,  1.03569737,  0.05133961],
       [ 0.02030724,  0.99713876,  1.04394462,  0.66494267, -0.58065889,
        -1.39419816,  1.00863325, -1.01804343,  1.1053115 ],
       [ 0.08062406,  0.99713876,  1.04394462,  0.66494267,  1.72218149,
         1.22443706, -0.99144064, -1.01804343, -1.00263229],
       [-0.13048482,  0.99713876, -0.95790522,  0.66494267, -0.58065889,
         0.07878415,  1.00863325,  1.03569737, -1.00263229],
       [ 0.1710993 ,  0.99713876,  1.04394462,  0.66494267, -0.58065889,
         0.07878415, -0.99144064,  1.03569737, -1.00263229],
       [-0.70349463,  0.99713876, -0.95790522, -1.50388904, -0